---
- name: Install GPG packages
  apt:
    name:
      - gnupg
      - apt-transport-https
    state: present
  become: true
  register: apt_result
  until: apt_result is success
  retries: 10
  delay: 2

- name: Import APT GPG keys by URL
  apt_key:
    url: "{{ item.url }}"
    keyring: "{{ item.keyring }}"
    state: present
  when: item.url is defined and item.url|length > 0
  with_items:
    - "{{ csstudio_repository_keys }}"
  become: true
  register: gpg_import_url
  until: gpg_import_url is success
  retries: 10
  delay: 2

- name: Import APT GPG keys by keyserver
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
    state: present
  when: item.keyserver is defined and item.keyserver|length > 0
  with_items:
    - "{{ csstudio_repository_keys }}"
  become: true
  register: gpg_import_key
  until: gpg_import_key is success
  retries: 10
  delay: 2

- name: Add Java 8 repositories
  apt_repository:
    repo: "{{ item.baseurl }}"
    state: "{{ item.state }}"
    filename: "{{ item.file }}"
    update_cache: true
  with_items:
    - "{{ csstudio_repository_apt }}"
  become: true

- name: Install Oracle Java packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  become: true
  register: apt_result
  until: apt_result is success
  retries: 10
  delay: 2

- name: Ensure Java packages are marked as hold
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ csstudio_deb_java_hold_packages }}"
  become: true
