---
__qt_install_from_src: true

__pyqt_install_from_src: true

__pyqt_dep_packages:
  - "liblapack-dev=3.7.0*"
  - "libdbus-1-3={{ pkg_version_libdbus_1_3 }} ""
  - "libglu1-mesa-dev={{ pkg_version_libglu1_mesa_dev }}""

__qt_distro_packages:
  - "qt5-default=5.7.1*"
  - "qttools5-dev-tools=5.7.1*"
  - "sip-dev=4.18.1*"
  - "python3-pyqt5.qtsvg=5.7*"
  - "libqt5opengl5-dev={{ pkg_version_libqt5opengl5_dev }}"
  - "qt5-qmake=5.7.1*"
  - "qtbase5-dev=5.7.1*"

__qt_pip_packages:
  - "PyQt5=={{ pkg_version_PyQt5 }}"
  - "PyQt5-sip=={{ pkg_version_PyQt5_sip }}"

__python_executable: python-sirius

__pip_executable: pip-sirius
