---
- name: "Ensure repository {{ item.repo_name }} is cloned"
  git:
    repo: "{{ item.org_url }}/{{ item.repo_name }}"
    dest: "{{ item.clone_path }}/{{ item.repo_name }}"
    version: "{{ item.repo_version | default('master') }}"
    accept_hostkey: "{{ item.git_accept_hostkey | default(omit) }}"
    ssh_opts: "{{ item.git_ssh_opts | default(omit) }}"
  register: git_result

- name: "Define {{ item.repo_name }} chdir variable"
  set_fact:
    repo_install_chdir: "{{ item.install_chdir | default('') }}"

- name: "Install {{ item.repo_name }} via Makefile"
  command: make install
  args:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
  become: true
  when: item.install_via_makefile is defined and
        (item.install_via_makefile | bool) and
        git_result.changed

- name: "Install {{ item.repo_name }} via setup.py"
  command: "{{ python_executable }} setup.py install"
  args:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
  become: true
  when: item.install_via_setup is defined and
        (item.install_via_setup | bool) and
        git_result.changed

- name: "Install {{ item.repo_name }} via custom command"
  command: "{{ item.install_via_custom }}"
  args:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
  become: true
  when: item.install_via_custom is defined and
        item.install_via_custom | length > 0 and
        git_result.changed
