---
sirius_hla_apps:

  - name: Math Phys
    org_url: https://github.com/lnls-fac
    repo_name: mathphys
    repo_version: master
    clone_path: /tmp
    install_via_setup: true

  - name: Development Packages
    org_url: https://github.com/lnls-sirius
    repo_name: dev-packages
    repo_version: master
    clone_path: /tmp
    install_chdir: siriuspy
    install_via_setup: true


  - name: Ethernet PRU-Serial 485 Application
    org_url: https://github.com/lnls-sirius
    repo_name: eth-bridge-pru-serial485
    repo_version: master
    clone_path: /tmp
    install_chdir: client
    install_via_setup: true

  - name: Machine Applications
    org_url: https://github.com/lnls-sirius
    repo_name: machine-applications
    repo_version: master
    clone_path: /tmp
    install_via_makefile: true


  - name: PyDM Package
    org_url: https://github.com/lnls-sirius
    repo_name: pydm
    repo_version: master
    clone_path: /tmp
    install_via_setup: true

  - name: High-Level Applications
    org_url: https://github.com/lnls-sirius
    repo_name: hla
    repo_version: master
    clone_path: /tmp
    install_chdir: pyqt-apps
    install_via_makefile: true


  - name: Scripts
    org_url: https://github.com/lnls-sirius
    repo_name: scripts
    repo_version: master
    clone_path: /tmp
    install_via_makefile: true
