---
- name: "Install {{ item.repo_name }} via Makefile"
  command: make install
  args:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
  become: true
  when: item.install_via_makefile is defined and
        (item.install_via_makefile | bool)
  listen: "Install app repository"

- name: "Install {{ item.repo_name }} via setup.py"
  command: "{{ python_executable }} setup.py install"
  args:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
  become: true
  when: item.install_via_setup is defined and
        (item.install_via_setup | bool)
  listen: "Install app repository"

- name: "Install {{ item.repo_name }} via custom command"
  command: "{{ item.install_via_custom }}"
  args:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
  become: true
  when: item.install_via_custom is defined and
        item.install_via_custom | length > 0
  listen: "Install app repository"
