---
sudo: required
language: python
services:
  - docker

# Set CI_TIME: true to enable build-step profiling in Travis
# Set CI_TRACE: true to enable shell script tracing in Travis
env:
  global:
    - DNS_SERVER1: 1.1.1.1
    - DNS_SERVER2: 8.8.8.8
    - CI_TIME: false
    - CI_TRACE: false
  matrix:
    - MOLECULE_DISTRO: centos:7
      BUILD_TYPE: default
    - MOLECULE_DISTRO: centos:7
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: fedora:28
      BUILD_TYPE: default
    - MOLECULE_DISTRO: fedora:28
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: fedora:29
      BUILD_TYPE: default
    - MOLECULE_DISTRO: fedora:29
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: debian:jessie
      BUILD_TYPE: default
    - MOLECULE_DISTRO: debian:jessie
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: ubuntu:precise
      BUILD_TYPE: default
    - MOLECULE_DISTRO: ubuntu:precise
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: ubuntu:trusty
      BUILD_TYPE: default
    - MOLECULE_DISTRO: ubuntu:trusty
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: ubuntu:xenial
      BUILD_TYPE: default
    - MOLECULE_DISTRO: ubuntu:xenial
      BUILD_TYPE: debug

    - MOLECULE_DISTRO: ubuntu:bionic
      BUILD_TYPE: default
    - MOLECULE_DISTRO: ubuntu:bionic
      BUILD_TYPE: debug

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule docker-py

# Hand off to generated script for each BUILD_TYPE
script:
  - ./ci_build.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
