---
sudo: required
language: python
services:
  - docker

# Set CI_TIME: true to enable build-step profiling in Travis
# Set CI_TRACE: true to enable shell script tracing in Travis
env:
  global:
    - DNS_SERVER1: 1.1.1.1
    - DNS_SERVER2: 8.8.8.8
    - CI_TIME: false
    - CI_TRACE: false
  matrix:

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-users

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-users

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-nfsclient

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-nfsclient

    # lnls-ans-role-repositories already
    # has Ubuntu and Debian testing by molecule,
    # as it runs different tests for each distro.
    # So, we don't need to create builds for each
    # one of them.
    - BUILD_TYPE: default
      ROLE: lnls-ans-role-repositories

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-epics

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-epics

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-python

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-python

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-java

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-java

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-cs-studio

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-cs-studio

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-qt

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-qt

    - MOLECULE_DISTRO: debian:buster
      BUILD_TYPE: default
      ROLE: lnls-ans-role-sirius-hla

    - MOLECULE_DISTRO: debian:stretch
      BUILD_TYPE: default
      ROLE: lnls-ans-role-sirius-hla

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule docker-py

# Hand off to generated script for each BUILD_TYPE
script:
  - ./ci_build.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
