---
- hosts: lnls560-linux
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-as-ps-dclink-tbts.service
      - sirius-ioc-tb-ps-correctors.service
      - sirius-ioc-tb-ps-dipoles.service
      - sirius-ioc-tb-ps-quadrupoles.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
