---
- hosts: all
  tasks:
  - import_role:
      name: lnls-ans-role-nvidia-driver
    when: global_import_nvidia_driver_role | default(false)
  - import_role:
      name: lnls-ans-role-users
  - import_role:
      name: lnls-ans-role-ntp
  - import_role:
      name: lnls-ans-role-repositories
  - import_role:
      name: lnls-ans-role-nfsclient
  - import_role:
      name: lnls-ans-role-zabbix
  - import_role:
      name: lnls-ans-role-python
  - import_role:
      name: lnls-ans-role-qt
  - import_role:
      name: lnls-ans-role-epics
  - import_role:
      name: lnls-ans-role-java
  - import_role:
      name: lnls-ans-role-cs-studio
  - import_role:
      name: lnls-ans-role-phoebus
  - import_role:
      name: lnls-ans-role-sirius-apps
  - import_role:
      name: lnls-ans-role-desktop-apps
  - import_role:
      name: lnls-ans-role-desktop-settings
