---
- hosts: linac-opi
  become: true
  tasks:
  - import_role:
      name: lnls-ans-role-users
  - import_role:
      name: lnls-ans-role-repositories
  - import_role:
      name: lnls-ans-role-nfsclient
  - import_role:
      name: lnls-ans-role-python
  - import_role:
      name: lnls-ans-role-qt
  - import_role:
      name: lnls-ans-role-epics
  - import_role:
      name: lnls-ans-role-java
  - import_role:
      name: lnls-ans-role-cs-studio
  - import_role:
      name: lnls-ans-role-sirius-apps
  - import_role:
      name: lnls-ans-role-desktop-apps
