---
- hosts: all
  become: true
  tasks:
  - import_role:
      name: lnls-ans-role-users
  - import_role:
      name: lnls-ans-role-python
  - import_role:
      name: lnls-ans-role-repositories
  - import_role:
      name: lnls-ans-role-epics
