---
- hosts: lnls454-linux
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-bo-ma-correctors-ia01.service
      - sirius-ioc-bo-ma-correctors-ia02.service
      - sirius-ioc-bo-ma-correctors-ia04.service
      - sirius-ioc-bo-ma-correctors-ia05.service
      - sirius-ioc-bo-ma-correctors-ia07.service
      - sirius-ioc-bo-ma-correctors-ia08.service
      - sirius-ioc-bo-ma-correctors-ia10.service
      - sirius-ioc-bo-ma-correctors-ia11.service
      - sirius-ioc-bo-ma-correctors-ia13.service
      - sirius-ioc-bo-ma-correctors-ia14.service
      - sirius-ioc-bo-ma-correctors-ia16.service
      - sirius-ioc-bo-ma-correctors-ia17.service
      - sirius-ioc-bo-ma-correctors-ia20.service
      - sirius-ioc-bo-ma-dipoles.service
      - sirius-ioc-bo-ma-quadrupoles.service
      - sirius-ioc-bo-ma-sextupoles.service
      - sirius-ioc-tb-ma-correctors.service
      - sirius-ioc-tb-ma-dipoles.service
      - sirius-ioc-tb-ma-quadrupoles.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name : "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
