---
# Install from source
__python_install_from_src: false

__basic_packages:
  - "git={{ pkg_version_git }}"
  - "build-essential={{ pkg_version_build_essential }}"

__python_dep_packages:
  - "libreadline5=5.2*"
  - "libreadline-dev=7.0-5*"
  - "libncursesw5-dev=6.1+20181013-2*"
  - "libssl-dev=1.1.1c-1*"
  - "libsqlite3-dev=3.27.2-3*"
  - "tk-dev=8.6.9+1*"
  - "libgdbm-dev=1.18.1-4*"
  - "libc6-dev={{ pkg_version_libc6_dev }}"
  - "libbz2-dev={{ pkg_version_libbz2_dev }}"

__python_base_packages:
  - python3-dev=3.7.3-1*

# We may need to install python2 setuptools because of ansible issue:
# https://github.com/ansible/ansible/issues/47361
__python_packages:
  - "python3-pip=18.1-5*"
  - "python3-tk=3.7.3*"
  # - python-setuptools={{ pkg_version_setuptools }}
  - "swig=3.0.12*"

__pip_executable: pip-sirius

__python_pip_packages:
  - "cairocffi=={{ pkg_version_cairocffi }}"
  - "jupyter=={{ pkg_version_jupyter }}"
  - "setuptools=={{ pkg_version_setuptools }}"
  - "matplotlib=={{ pkg_version_matplotlib }}"
  - "pandas=={{ pkg_version_pandas }}"
  - "psutil=={{ pkg_version_psutil }}"
  - "pyqtgraph=={{ pkg_version_pyqtgraph }}"
  - "python-nmap=={{ pkg_version_python_nmap }}"
  - "requests=={{ pkg_version_requests }}"
  - "scipy=={{ pkg_version_scipy }}"
  - "sh=={{ pkg_version_sh }}"
  - "termcolor=={{ pkg_version_termcolor }}"
  - "wakeonlan=={{ pkg_version_wakeonlan }}"
  - "xlrd=={{ pkg_version_xlrd }}"
