---
__basic_packages:
  - git

__python_dep_packages:
  - libreadline-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev

__python_packages:
  - python3-dev
  - python3-pip
  - python3-setuptools
  - swig
