---
# Install from source
__python_install_from_src: false

__basic_packages:
  - git
  - build-essential

__python_dep_packages:
  - libreadline-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev

__python_base_packages:
  - python3-dev

__python_packages:
  - python3-pip
  - python3-tk
  - python-setuptools
  - swig

__pip_executable: pip-sirius

__python_pip_packages:
  - setuptools
  - matplotlib
