---
# Install from source
__python_install_from_src: true

__basic_packages:
  - git=1:2.11.0*
  - "{{ package_build_essential }}"

__python_dep_packages:
  - libreadline5=5.2*
  - libreadline-dev=7.0-3*
  - libncursesw5-dev=6.0+20161126-1*
  - libssl-dev=1.1.0k-1*
  - libsqlite3-dev=3.16.2-5*
  - tk-dev=8.6.0+9*
  - libgdbm-dev=1.8.3-14*
  - libc6-dev=2.24-11*
  - libbz2-dev=1.0.6-8.1*

__python_base_packages:
  - python3-dev=3.5.3-1*

# We may need to install python2 setuptools because of ansible issue:
# https://github.com/ansible/ansible/issues/47361
__python_packages:
  - python3-pip=9.0.1-2*
  - python3-tk=3.5.3*
  - python-setuptools=33.1.1-1*
  - swig=3.0.10*

__pip_executable: pip-sirius

__python_pip_packages:
  - cairocffi==1.0.2
  - jupyter==1.0.0
  - setuptools==41.2.0
  - matplotlib==3.0.2
  - pandas==0.24.1
  - psutil==5.5.0
  - pyqtgraph==0.10.0
  - python-nmap==0.6.1
  - requests==2.21.0
  - scipy==1.2.1
  - sh==1.12.14
  - termcolor==1.1.0
  - wakeonlan==1.1.6
  - xlrd==1.2.0
