---
- name: Install LDAP auth and secure TTY PAM stacks
  template:
    src: "pam/{{ ldap_pam_templates[ansible_distribution] }}/{{ item }}.j2"
    dest: "/etc/pam.d/{{ item }}"
    mode: 0644
  with_items:
    - login
    - ldap-auth
  tags:
    - config

- name: Configure PAM system and password auth to use LDAP
  file:
    src: ldap-auth
    dest: "/etc/pam.d/{{ item }}"
    state: link
    force: true
  with_items:
    - system-auth
    - password-auth
  tags:
    - config
