---
- name: Create groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ users_groups }}"
  when: item.state|default('present') != "absent"

- name: Create user groups if enabled
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid | default(item.uid) | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ users }}"
  when: >
    (users_per_user_groups == true or
    item.group|default('justAPlaceHolder') == 'justAPlaceHolder') and
    item.state|default('present') != 'absent'
