---
- name: Remove group
  group:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ users_groups }}"
  when: item.state|default('present') == "absent"

- name: Remove user groups
  group:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ users }}"
  when: >
    users_per_user_groups and
    item.state|default('present') == 'absent' and
    item.name != ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true)
  become: true
