---
- name: Ensure ssh packages are installed
  package:
    name: "{{ ssh_packages }}"
    state: present
  become: true
  register: package_result
  until: package_result is success
  retries: 10
  delay: 2
