---
nfs_clients_control_room_subnet: ""
nfs_clients_cnpem_sirius_subnet: ""
fac_workstation_ip: ""

# Set this to true when using this in a regular,
# without systemd support.
nfs_ignore_systemd_errors: false

nfs_config_files:
  - name: NFS server exports file
    filename: exports
    pathname: "/etc"
