---
__desktop_packages:
  - rdesktop
  - htop
  - vim
  - ipython3
  - remmina
  - remmina-plugin-rdp
  - remmina-plugin-secret
  - code
  - ca-certificates
  - gconf2
  - libasound2
  - libgtk2.0-0
  - libxss1
