---
__desktop_packages:
  - rdesktop=1.8.6*
  - htop=2.2.0*
  - vim=2:8.1.0875*
  - ipython3=5.8.0*
  - remmina=1.3.3*
  - remmina-plugin-rdp=1.3.3*
  - remmina-plugin-secret=1.3.3*
  - code=1.36.1*
  - tightvncserver=1:1.3.9*
  - lightdm=1.26.0*
  - ca-certificates
  - gconf2
  - libasound2
  - libgtk2.0-0
  - libxss1
  - libffi6
  - libffi-dev
  - libfreetype6
  - libfreetype6-dev
  - nmap
  - dvipng
  - sshpass
  - wait-for-it

__desktop_pip_packages:
  - python-nmap
  - wakeonlan
  - requests
  - pyqtgraph
  - pandas
  - psutil
  - termcolor
  - sh
  - cairocffi
  - matplotlib
  - scipy
  - jupyter
  - xlrd

__pip_executable: pip-sirius
