---
ldap_ca_path:
  Fedora: &rhcapath /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  Scientific: *rhcapath
  Debian: /etc/ssl/certs/ca-certificates.crt
ldap_sudo_ldap_conf:
  Scientific: /etc/sudo-ldap.conf
  Fedora: /etc/ldap.conf
  Debian: /etc/sudo-ldap.conf
ldap_conf:
  Fedora: &rhldapconf /etc/openldap/ldap.conf
  Scientific: *rhldapconf
  Debian: /etc/ldap/ldap.conf
ldap_nslcd_user:
  Fedora: &nslcdusr
    uid: nslcd
    gid: ldap
  Scientific: *nslcdusr
  Debian:
    uid: nslcd
    gid: nslcd
ldap_pam_param_short_name: true
ldap_pam_param_config_file: /etc/security/pam_param.ini
ldap_pubkey_filter: (&(objectClass=ldapPublicKey)(uid=%s))
ldap_pubkey_attr: sshPublicKey
ldap_sshd_config:
  AuthorizedKeysCommand:
    Debian: /usr/lib/getauthorizedkeys/getauthorizedkeys
    RedHat: /usr/libexec/getauthorizedkeys
  AuthorizedKeysCommandUser:
    Debian: nobody
    RedHat: nobody
ldap_sudoers: true
ldap_uid_min: 1000
ldap_pam_templates:
  Fedora: &rhtemplates RedHat
  Scientific: *rhtemplates
  Debian: Debian
ldap_packages:
  Fedora: &rhpackages
    - nss-pam-ldapd
    - openldap
    - openldap-clients
    - pam-param
    - getauthorizedkeys
  Scientific: *rhpackages
  Debian:
    - nslcd
    - libnss-ldapd
    - libpam-ldapd
    - sudo-ldap
    - ldap-utils
    - libpam-param
    - getauthorizedkeys
