---
# NTP daemon package name
ntp_daemon: "{{ pkg_version_ntp }}"

# This is left unversioned as this package is updated
# periodically to reflect changes made by political bodies
# to time zone boundaries
ntp_tzdata_package: tzdata

ntp_driftfile: /var/lib/ntp/drift
