---
- name: Create Qt installation directory
  file:
    path: "{{ qt_src_dir_path }}"
    state: directory

- name: Download Qt installation script
  get_url:
    url: "{{ qt_src_download_url }}"
    dest: "{{ qt_src_dir_path }}/{{ qt_src_remote_script }}"
    checksum: "{{ qt_src_checksum }}"
    mode: '0744'
  notify: "Install Qt from source"

- name: Install Qt support installation files
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.pathname }}/{{ item.filename }}"
  with_items:
    - "{{ qt_src_support_install_files }}"

- name: Force handlers to run at this point
  meta: flush_handlers
