---
- name: Ensure no PyQt Pip versions are installed
  pip:
    name: "{{ qt_pip_packages | regex_replace('==.*$', '') }}"
    state: absent
    executable: "{{ pip_executable }}"
  become: true
  register: qt_pip_packages_result
  until: qt_pip_packages_result is success
  retries: 5
  delay: 2
