---
# Use a loop here, as we might fail if some package is missing
- name: Ensure no Qt system versions are installed
  apt:
    name: "{{ item | regex_replace('=.*$', '') }}"
    state: absent
    purge: true
  become: true
  ignore_errors: true
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 2
  with_items:
    - "{{ qt_distro_packages }}"
