---
- name: Restart VNC server systemd services
  block:
    - name: Restart VNC server systemd services
      systemd:
        name: "{{ item.name }}"
        state: restarted
      with_items:
        - "{{ desktop_vnc_server_services }}"
  become: true
  ignore_errors: "{{ desktop_vnc_ignore_systemd_errors }}"
  rescue:
    - name: Show warning to user if systemd fails
      pause:
        seconds: 1
        echo: false
        prompt: "Could not reload desktop_vnc systemd service. Probably running in Docker? Continuing anyway ..."
