---
# EPICS package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_apps_epics_packages_state: present

# PIP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_apps_epics_pip_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
sirius_apps_epics_install_recommends: true

# Sirius Linac EDM screens
sirius_apps_li_edm_dir: /usr/local/share/edm/data

# Sirius designer path
sirius_apps_designer_dir: /usr/local/share/Qt/designer

# Groups of packages
sirius_apps_dev_packages:

  - name: Math Phys
    org_url: https://github.com/lnls-fac
    repo_name: mathphys
    repo_version: master
    clone_path: /tmp
    install_via_setup: true
    setup_extra_args: "--no-deps"
    repo_cvs: git+
    force_version: true

  - name: Development Packages
    org_url: https://github.com/lnls-sirius
    repo_name: dev-packages
    repo_version: master
    clone_path: /tmp
    install_chdir: siriuspy
    install_via_setup: true
    setup_extra_args: "--no-deps"
    repo_cvs: git+
    force_version: true

sirius_apps_iocs:

  - name: Ethernet PRU-Serial 485 Application
    org_url: https://github.com/lnls-sirius
    repo_name: eth-bridge-pru-serial485
    repo_version: master
    clone_path: /tmp
    install_chdir: client
    install_via_setup: true
    setup_extra_args: "--no-deps"
    repo_cvs: git+
    force_version: true

  - name: Machine Applications
    org_url: https://github.com/lnls-sirius
    repo_name: machine-applications
    repo_version: master
    clone_path: /tmp
    install_via_makefile: true
    force_version: true

sirius_apps_hla:

  - name: PyDM Package
    org_url: https://github.com/lnls-sirius
    repo_name: pydm
    repo_version: master
    clone_path: /tmp
    install_via_setup: true
    setup_extra_args: "--no-deps"
    repo_cvs: git+
    force_version: true

  - name: High-Level Applications
    org_url: https://github.com/lnls-sirius
    repo_name: hla
    repo_version: master
    clone_path: /tmp
    install_chdir: pyqt-apps
    install_via_makefile: true
    make_install_target: install-all
    make_install_opts:
      INSTALL_DESIGNER_DIR: "{{ sirius_apps_designer_dir }}"
    force_version: true

  - name: PyDM timechart Package
    org_url: https://github.com/slaclab
    repo_name: timechart
    repo_version: v1.2.2
    clone_path: /tmp
    install_via_setup: true
    setup_extra_args: "--no-deps"
    repo_cvs: git+
    force_version: true

sirius_apps_opis:

  - name: OPIs
    org_url: https://gitlab.cnpem.br/FACS
    repo_name: linac-opi
    repo_version: master
    clone_path: /tmp
    install_via_makefile: true
    make_install_target: install-default
    make_install_opts:
      INSTALL_EDM_DIR: "{{ sirius_apps_li_edm_dir }}"
    force_version: true

sirius_apps_mgmt:

  - name: Scripts
    org_url: https://github.com/lnls-sirius
    repo_name: scripts
    repo_version: master
    clone_path: /tmp
    install_via_makefile: true
    force_version: true

# Select which categories to install. Defaults to all
sirius_apps_install_categories:
  - sirius_apps_dev_packages
  - sirius_apps_iocs
  - sirius_apps_hla
  - sirius_apps_opis
  - sirius_apps_mgmt

sirius_apps_config_files:
  - name: Sirius Apps environment variables
    filename: sirius_apps.sh
    pathname: "/etc/profile.d"

  - name: Sirius Apps Linac EDM variables
    filename: linac_edm.sh
    pathname: "/etc/profile.d"
