---
- name: Ensure cursor is updated
  alternatives:
    name: x-cursor-theme
    path: "{{ desktop_settings_cursor_theme_alternative }}"

- name: Add cursor size to Xresources
  lineinfile:
    state: present
    path: /etc/X11/Xresources/x11-common
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - "{{ desktop_settings_xresources_lines | default([]) }}"
