---
- hosts: ioc_bo_ps_fams_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-bo-ps-dipole-1.service
      - sirius-ioc-bo-ps-dipole-2.service
      - sirius-ioc-bo-ps-quadrupole-qd.service
      - sirius-ioc-bo-ps-quadrupole-qf.service
      - sirius-ioc-bo-ps-sextupole-sf.service
      - sirius-ioc-bo-ps-sextupole-sd.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
