---
- hosts: ioc_tb_ma_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-tb-ma-dipoles.service
      - sirius-ioc-tb-ma-quadrupoles.service
      - sirius-ioc-tb-ma-correctors.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
