---
- hosts: ioc_ts_ps_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-ts-ps-dipoles.service
      - sirius-ioc-ts-ps-quadrupoles-12.service
      - sirius-ioc-ts-ps-quadrupoles-34.service
      - sirius-ioc-ts-ps-correctors.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
