---
- hosts: ioc_as_pm_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-tb-pm-injsept.service
      - sirius-ioc-bo-pm-injkckr.service
      - sirius-ioc-bo-pm-ejekckr.service
      - sirius-ioc-ts-pm-ejeseptf.service
      - sirius-ioc-ts-pm-ejeseptg.service
      - sirius-ioc-ts-pm-injseptf.service
      - sirius-ioc-ts-pm-injseptg1.service
      - sirius-ioc-ts-pm-injseptg2.service
      - sirius-ioc-si-pm-injdpkckr.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
