---
- hosts: ioc_si_ma_fams_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-si-ma-dipoles.service
      - sirius-ioc-si-ma-quadrupoles-qd1.service
      - sirius-ioc-si-ma-quadrupoles-qd2.service
      - sirius-ioc-si-ma-quadrupoles-qf.service
      - sirius-ioc-si-ma-quadrupoles-q.service
      - sirius-ioc-si-ma-sextupoles-sda12b2.service
      - sirius-ioc-si-ma-sextupoles-sfa0p0-sda0p0.service
      - sirius-ioc-si-ma-sextupoles-sfa12-sda3p1.service
      - sirius-ioc-si-ma-sextupoles-sfb0-sdb01.service
      - sirius-ioc-si-ma-sextupoles-sfb12-sdb3.service
      - sirius-ioc-si-ma-sextupoles-sfp12-sdp23.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
