---
- name: Reload NFS server systemd service
  block:
    - name: Reload NFS server systemd service
      systemd:
        name: autofs
        state: reloaded
  become: true
  ignore_errors: "{{ nfs_ignore_systemd_errors }}"
  rescue:
    - name: Show warning to user if systemd fails
      pause:
        seconds: 1
        echo: false
        prompt: "Could not reload NFS systemd service. Probably running in Docker? Continuing anyway ..."
