---
__sirius_apps_epics_packages:
  - xpra=2.4.3*
  # - winswitch
  - xvfb=2:1.20.4*
  - bc=1.07.1*

__sirius_apps_epics_pip_packages: []

__python_executable: python-sirius

__pip_executable: pip-sirius
