---
__sirius_apps_epics_packages:
  - epics-extensions-dev
  - edm-dev
  - xpra
  - xvfb
  - bc

__sirius_apps_epics_pip_packages:
  - "pydm=={{ pkg_version_pydm }}"
  - "timechart=={{ pkg_version_timechart }}"

__python_executable: python-sirius

__pip_executable: pip-sirius
