---
dependency:
  name: galaxy
lint:
  name: yamllint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      default_group:
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
driver:
  name: docker
platforms:
  - name: lnls-ans-role-nfsclient-instance
    image: "${MOLECULE_DISTRO:-debian:stretch}"
    command: "${MOLECULE_DOCKER_COMMAND:-''}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabiolities:
      - SYS_ADMIN
    groups:
      - default_group
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]
