---
nfs_server_control_room: 10.128.254.205
nfs_server_control_opi: 10.128.1.3

nfs_config_files:
  - name: Autofs file autofs.conf
    filename: autofs.conf
    pathname: "/etc"
  - name: Autofs file auto.master
    filename: auto.master
    pathname: "/etc"
  - name: Autofs file auto.sirius
    filename: auto.sirius
    pathname: "/etc"
