---
# EPICS base directory
epics_base_dir: /usr/lib/epics

# Host architecture for EPICS
epics_host_arch: linux-x86_64

# EPICS package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
epics_packages_state: present

# PIP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
epics_pip_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
epics_install_recommends: true

# Additional EPICS packages
epics_packages_extra: []
