---
- name: create config directories for users
  become: yes
  become_user: '{{ item.0.username }}'
  file:
    path: '~{{ item.0.username }}/{{ visual_studio_code_config_path }}'
    state: directory
    mode: 'u=rwx,go=r'
  with_subelements:
    - '{{ visual_studio_code_users }}'
    - visual_studio_code_extensions
    - skip_missing: yes
  loop_control:
    label: "{{ item.0.username }} => {{ item.1 }}"

- name: create settings directory
  become: yes
  become_user: '{{ item.username }}'
  file:
    path: '~{{ item.username }}/{{ visual_studio_code_config_path }}/User'
    state: directory
    mode: 'u=rwx,go=r'
  with_items: '{{ visual_studio_code_users }}'
  loop_control:
    label: "{{ item.username }}"

- name: write settings
  become: yes
  become_user: '{{ item.username }}'
  template:
    src: settings.json.j2
    dest: '~{{ item.username }}/{{ visual_studio_code_config_path }}/User/settings.json'
    force: yes
    mode: 'u=rw,go=r'
  with_items: '{{ visual_studio_code_users }}'
  when: "item.visual_studio_code_settings is defined and item.visual_studio_code_settings not in ({}, '', None, omit)"
  loop_control:
    label: "{{ item.username }}"

- name: write keybindings
  become: yes
  become_user: '{{ item.username }}'
  template:
    src: keybindings.json.j2
    dest: '~{{ item.username }}/{{ visual_studio_code_config_path }}/User/keybindings.json'
    force: yes
    mode: 'u=rw,go=r'
  with_items: '{{ visual_studio_code_users }}'
  when: "item.visual_studio_code_keybindings is defined and item.visual_studio_code_keybindings not in ({}, '', None, omit)"
  loop_control:
    label: "{{ item.username }}"
