---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: apt_update_cache_result
  until: apt_update_cache_result is success
  retries: 5
  delay: 2

- name: Ensure Desktop packages are installed
  apt:
    name: "{{ desktop_packages }}"
    state: "{{ desktop_packages_state }}"
    install_recommends: "{{ desktop_install_recommends }}"
    default_release: "{{ desktop_default_release | default(omit) }}"
  become: true
  register: apt_packages_result
  until: apt_packages_result is success
  retries: 5
  delay: 2

- name: Check defined users
  debug:
    msg: "Defined users: {{ users | default([]) | list }}"

# This depends on the User's role. As the user module will not update the user
# directory with the /etc/skel contents if it's already created, just copy them
# manually
- name: Ensure files are copied to each user's home
  copy:
    src: "skel/"
    dest: "/home/{{ item.name }}"
    owner: "{{ item.name | default(omit) }}"
    group: "{{ item.name | default(omit) }}"
    mode: 0755
  with_items:
    - "{{ users }}"
