---
# This depends on the User's role. As the user module will not update the user
# directory with the /etc/skel contents if it's already created, just copy them
# manually
- name: Ensure files are copied to each user's home
  copy:
    src: "skel/"
    dest: "/home/{{ item.name }}"
    owner: "{{ item.name | default(omit) }}"
    group: "{{ item.name | default(omit) }}"
    mode: 0755
  with_items:
    - "{{ users }}"

- name: Install VNC server config files
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.pathname }}/{{ item.filename }}"
    owner: root
    group: root
    force: true
    mode: 0644
  become: true
  with_items:
    - "{{ desktop_vnc_config_files }}"
  when: apt_result is success
  notify: Reload VNC server systemd service

- name: Enable VNC server systemd service
  systemd:
    name: vncserver@1
    state: started
    enabled: true
  become: true
  register: systemd_enable
  ignore_errors: "{{ desktop_vnc_ignore_systemd_errors }}"

- name: Show warning to user if systemd fails
  pause:
    seconds: 1
    echo: false
    prompt: "Could not enable VNC systemd service. Probably running in Docker? Continuing anyway ..."
  when: systemd_enable is failed
