---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: apt_update_cache_result
  until: apt_update_cache_result is success
  retries: 5
  delay: 2

- name: Add Debian repositories
  apt_repository:
    repo: "{{ item.baseurl }}"
    state: "{{ item.state }}"
    filename: "{{ item.file | default(omit) }}"
    update_cache: true
  with_items:
    - "{{ nvidia_repository_apt }}"
  become: true

- name: Ensure Nvidia packages are installed
  apt:
    name: "{{ nvidia_packages }}"
    state: present
  become: true
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 2
